# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Insurance1
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Insurance1MSP

        # ID to load the MSP definition as
        ID: Insurance1MSP

        MSPDir: ../organizations/peerOrganizations/insurance1.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Insurance1MSP.admin', 'Insurance1MSP.peer', 'Insurance1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Insurance1MSP.admin', 'Insurance1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Insurance1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Insurance1MSP.peer')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.insurance1.com
              Port: 13051
